"""Add mcc field to transactions

Revision ID: f64746021b4e
Revises: 0001_initial_schema
Create Date: 2026-07-08 18:35:53.502786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64746021b4e'
down_revision: Union[str, Sequence[str], None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_holdings_symbol'), table_name='holdings')
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.drop_index(op.f('idx_payees_name'), table_name='payees')
    op.create_index(op.f('ix_payees_name'), 'payees', ['name'], unique=False)
    op.drop_constraint(op.f('sync_configs_name_key'), 'sync_configs', type_='unique')
    op.drop_index(op.f('idx_sync_runs_started_at'), table_name='sync_runs')
    op.drop_index(op.f('idx_sync_runs_sync_config_id'), table_name='sync_runs')
    op.alter_column('transaction_splits', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('transactions', sa.Column('mcc', sa.String(length=4), nullable=True))
    op.drop_index(op.f('idx_transactions_account_id'), table_name='transactions')
    op.drop_index(op.f('idx_transactions_posted'), table_name='transactions')
    op.create_index(op.f('ix_transactions_posted'), 'transactions', ['posted'], unique=False)
    op.drop_constraint(op.f('transactions_payee_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'payees', ['payee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_payee_id_fkey'), 'transactions', 'payees', ['payee_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_transactions_posted'), table_name='transactions')
    op.create_index(op.f('idx_transactions_posted'), 'transactions', ['posted'], unique=False)
    op.create_index(op.f('idx_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.drop_column('transactions', 'mcc')
    op.alter_column('transaction_splits', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('idx_sync_runs_sync_config_id'), 'sync_runs', ['sync_config_id'], unique=False)
    op.create_index(op.f('idx_sync_runs_started_at'), 'sync_runs', ['started_at'], unique=False)
    op.create_unique_constraint(op.f('sync_configs_name_key'), 'sync_configs', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_payees_name'), table_name='payees')
    op.create_index(op.f('idx_payees_name'), 'payees', ['name'], unique=False)
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.create_index(op.f('idx_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    # ### end Alembic commands ###
